routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => '', 'as' => 'doctors.'], function (){
    Route::get('/', 'DoctorsController@index')->name('list');
    Route::get('/ajax/filter', 'DoctorsController@ajaxFilter')->name('filter');
    Route::get('/ajax/{doctor}/card', 'DoctorsController@ajaxDoctorCard')->name('card');


});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function doctors() {
        return $this->belongsToMany(Doctor::class, 'category_doctor');
    }

}

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    public function scopePublished() {
        return $this->where('active', true);
    }
    public function categories() {
        return $this->belongsToMany(Category::class, 'category_doctor');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DoctorsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Doctor;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DoctorsController extends Controller
{

    public function index(Request $request)
    {
        $doctors = Doctor::with('categories')->published()->orderBy('price_30_min', 'desc')->paginate(12);
        $categories = Category::pluck('name', 'id')->toArray();
     return view('frontend.doctors.index', compact('doctors', 'categories'));

    }

    public function ajaxFilter(Request $request)
    {
        $doctors = Doctor::with('categories')->published();
        if($name = $request->doctor){
            $doctors->where('name', 'like', '%' . $name . '%');
        }
        if($request->category && $request->category != 'all'){
            $doctors->whereHas('categories', function ($q) use ($request) {
                $q->where('id', (int) $request->category);
            });
        }

        if($sort = $request->sort_price){
            $doctors->orderBy('price_30_min', $sort);
        }
        $doctors = $doctors->get();

        $view = view('frontend.doctors.partials.results', compact('doctors'))->render();
        return response()->json(['success' => true, 'message' => 'success', 'data' => $view]);
    }

    public function ajaxDoctorCard(Doctor $doctor)
    {
        return view('frontend.doctors.partials.doctor_card', compact('doctor'));
    }

}

resources/views/frontend/doctors/index.blade.php
@extends('frontend.layouts.master')

@section('content')
    @include('frontend.doctors.partials.steps_section')
<!-- Doctors Section Start -->
<section class="blog-section bg-f8 pt-30">
    <div class="container">
<form id="get-doctors-results-form" action="{{route('doctors.filter')}}">
        <div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">

            <div class="row">

                <div class="col-md-3">

                    <div class="checkbox-container circular-container">

                        <h3 class="title-filter-box">التصنيف <span class="pull-left">مسح التصنيف</span></h3>

                        <div class="sidebar-section-title">

                            <svg-icon src="assets/images/search/time.svg" class="mr8 filter-icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" style="width: 25px;"><defs><style>.cls-1-clock{fill:#3da8c0;}.cls-2-clock,.cls-3-clock{fill:none;stroke:#fff;stroke-miterlimit:10;stroke-width:2px;}.cls-3-clock{stroke-linecap:round;}</style></defs><title>time</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><circle class="cls-1-clock" cx="25" cy="25" r="25"></circle><polyline class="cls-2-clock" points="25 11.21 25 25.44 37.85 31.29"></polyline><line class="cls-3-clock" x1="25" y1="4.24" x2="25" y2="5.61"></line><line class="cls-3-clock" x1="25" y1="45.15" x2="25" y2="46.52"></line><line class="cls-3-clock" x1="46.14" y1="25.38" x2="44.77" y2="25.38"></line><line class="cls-3-clock" x1="5.23" y1="25.38" x2="3.86" y2="25.38"></line><line class="cls-3-clock" x1="39.95" y1="10.43" x2="38.98" y2="11.4"></line><line class="cls-3-clock" x1="11.02" y1="39.36" x2="10.05" y2="40.32"></line><line class="cls-3-clock" x1="39.95" y1="40.32" x2="38.98" y2="39.36"></line><line class="cls-3-clock" x1="11.02" y1="11.4" x2="10.05" y2="10.43"></line></g></g></svg></svg-icon>
                            <span>المواعيد المتاحة والمدة</span>
                        </div>
                        <div class="d-flex">
                            <label class="checkbox-label">
                                <input type="checkbox">
                                <span class="checkbox-custom circular"></span>
                                <strong>اليوم</strong>
                            </label>
                            <label class="checkbox-label">
                                <input type="checkbox">
                                <span class="checkbox-custom circular"></span>
                                <strong>الاسبوع</strong>
                            </label>
                        </div>
                        <div class="mt-20">
                            <p>متاح من : اختر ميعاد</p>
                            <input type="text" name="date" class="form-control" placeholder="اختر التاريخ">
                        </div>

                        <div class="mt-20">
                            <p>متاح من : اختر ميعاد</p>
                            <input type="text" name="date" class="form-control" disabled placeholder="اختر التاريخ">
                        </div>

                        <p class="mt-20">المدة</p>

                        <div class="d-flex">
                            <label class="checkbox-label">
                                <input type="checkbox">
                                <span class="checkbox-custom circular"></span>
                                <strong>30 دقيقة</strong>
                            </label>
                            <label class="checkbox-label">
                                <input type="checkbox">
                                <span class="checkbox-custom circular"></span>
                                <strong>60 دقيقة</strong>
                            </label>
                        </div>

                    </div>
                    <!-- <div class="clear"></div> -->
                </div>
                <div class="col-md-9 cbp-vm-view-grid">
                    <div class="tools-ber">
                        <div class="row">
                            <div class="col-lg-4">
                                <!-- filters select -->
                                <div class="select-filters">

                                    <input type="text" name="doctor" class="form-control filter-input-name"  placeholder="&#xF002; بحث بأسم المعالج" style="font-family:Arial, FontAwesome">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <!-- filters select -->
                                <div class="select-filters">
                                    <select class="sort_price filter-input" id="sort-category" name="category">
                                        <option value="all">جميع التخصصات</option>
                                        @foreach($categories as $key => $value)
                                        <option value="{{$key}}">{{$value}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <!-- filters select -->
                                <div class="select-filters">
                                    <select name="sort_price" id="sort-price" class="filter-input">
                                        <option disabled="">رتب حسب</option>
                                        <option value="asc">السعر: من الأقل الى الأعلى</option>
                                        <option value="desc">السعر: من الأعلى الى الأقل</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row" id="doctors-section">
                       @foreach($doctors as $doctor)
                        <div class="col-lg-4">
                            @include('frontend.doctors.partials.doctor_grid')
                        </div>
                       @endforeach
                    </div>
                </div>

            </div>
        </div>


</form>
    </div>

</section>
<!-- Doctors Section End -->
    @endsection

    @section('js')
    <script>

        $(".filter-input").on('change',function(e) {

            e.preventDefault();

            getResults();


        });

        $(".filter-input-name").on('keyup',delayKeyUp(function(e) {
            getResults();


        }, 500));

        function getResults() {
            var form = $('#get-doctors-results-form');
            var url = form.attr('action');

            $.ajax({
                type: "GET",
                url: url,
                data: form.serialize(),
                success: function(response)
                {
                    $('#doctors-section').html(response.data)
                }
            });

        }

        function delayKeyUp(callback, ms) {
            var timer = 0;
            return function() {
                var context = this, args = arguments;
                clearTimeout(timer);
                timer = setTimeout(function () {
                    callback.apply(context, args);
                }, ms || 0);
            };
        }
        // $(".filter-input-name").on('click', function(e) {
        //     e.preventDefault();
        //      $('#doctorModal').modal()
        // });

        $('body').on("click", ".open-doctor-modal", function(e) {
            e.preventDefault();
            var btn = $(this);
            $("#doctorModal").modal().find(".modal-body").load(btn.data('url'));
        });


    </script>
    @endsection

resources/views/frontend/doctors/partials/doctor_card.blade.php
@php
    $doctorCategoriesArray = $doctor->categories->pluck('name')->toArray();
@endphp
<div class="row">

    <div class="col-md-12">

        <div class="row">
            <div class="col-md-4">
                <div class="thumb">
                    <a href="#"> <img
                            src="{{asset('media/'.$doctor->id.'.png')}}"
                            alt=""></a>
                </div>
            </div>
            <div class="col-md-8">
                <div class="content">
                    <div class="title-box">
                        <h4 class="doctor-grid-title text-blue">{{$doctor->name}}</h4>
                        <h3 class="doctor-desc">{{$doctor->description}}</h3>
                    </div>
                    <div class="review-stars row justify-content-center">
                        <div class="col-md-12 text-center-col mt-10">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <span>
4.82
(
220 تقييم)</span>

                        </div>

                        <div class="col-md-12 text-center-col">{{implode(" ,", $doctorCategoriesArray)}}</div>


                    </div>

                    <div class="mt-15">
                        <div class="text-center">
                            <i class="fa fa-money" style="color: #3bb54a;"></i>

                            <span class="pr-10"> جنيه {{$doctor->price_30_min}}/ 30 دقيقة   </span>-<span
                                class="pl-10">   جنيه  جنيه {{$doctor->price_60_min}}/ 60 دقيقة</span>
                        </div>

                    </div>


                </div>

            </div>

        </div>

        <div class="row">
            <div class="col-md-12 p-0 mt-20">
                <div class="buttons-group">
                    <div class="book pt-10 pb-10">This Week</div>
                    <div class="calender pt-10 pb-10 " tabindex="0">Calender</div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12 mt-10">
                <div class="d-flex justify-content-between">
                    <span class="font-bold font-size-14 text-black">برجاء اختيار موعد</span>
                    <span class="text-right text-black"><i class="fa fa-globe"></i> جميع المواعيد (Africa/Cairo) </span>
                </div>
            </div>
            <div class="col-md-4">

            </div>
        </div>


    </div>


</div>

resources/views/frontend/doctors/partials/doctor_grid.blade.php
@php
    $doctorCategoriesArray = $doctor->categories->pluck('name')->toArray();
@endphp
<div class="special-places">
    <div class="thumb">
        <a href="#"> <img
                src="{{asset('media/'.$doctor->id.'.png')}}"
                alt=""></a>
    </div>
    <div class="content">
        <div class="title-box">
            <h4 class="doctor-grid-title text-blue">{{$doctor->name}}</h4>
            <h3>{{$doctor->description}}</h3>
        </div>
        <div class="review-stars row justify-content-center">
            <div class="col-md-12 text-center-col mt-30">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <span>
 4.82 (220 تقييم)</span>

            </div>

            <div class="col-md-12 text-center-col">{{implode(" ,", $doctorCategoriesArray)}}</div>


        </div>

        <div class="mt-25">
            <div class="float-right">
                <svg-icon _ngcontent-serverapp-c130="" class="icon">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 51 26" style="width: 20px;">
                        <defs>
                            <style>.cls-1-fees {
                                    fill: #3da8c0;
                                }

                                .cls-2-fees, .cls-3-fees {
                                    fill: #fff;
                                }

                                .cls-3-fees {
                                    stroke: #fff;
                                    stroke-width: 0.8px;
                                }

                                .cls-3-fees, .cls-4-fees {
                                    stroke-miterlimit: 10;
                                }

                                .cls-4-fees {
                                    fill: none;
                                    stroke: #3da8c0;
                                }</style>
                        </defs>
                        <title>Egp</title>
                        <g id="Layer_2" data-name="Layer 2">
                            <g id="Layer_1-2" data-name="Layer 1">
                                <rect class="cls-1-fees" x="0.5" y="0.5" width="50" height="25" rx="2" ry="2"></rect>
                                <path class="cls-2-fees"
                                      d="M49.49.5a1,1,0,0,1,1,1v5.4a4.91,4.91,0,0,1-.86.08A5.63,5.63,0,0,1,44,1.36,4.91,4.91,0,0,1,44.09.5Z"></path>
                                <path class="cls-2-fees"
                                      d="M7,1.36A5.63,5.63,0,0,1,1.36,7,4.91,4.91,0,0,1,.5,6.91V1.84A1.34,1.34,0,0,1,1.84.5H6.91A4.91,4.91,0,0,1,7,1.36Z"></path>
                                <path class="cls-2-fees"
                                      d="M50.5,18.79V24.3a1.2,1.2,0,0,1-1.2,1.2H44.13A6.34,6.34,0,0,1,44,24.34a5.63,5.63,0,0,1,5.63-5.63A4.11,4.11,0,0,1,50.5,18.79Z"></path>
                                <path class="cls-2-fees"
                                      d="M7,24.34a6.34,6.34,0,0,1-.12,1.16H1.37a.87.87,0,0,1-.87-.87V18.79a4.11,4.11,0,0,1,.86-.08A5.63,5.63,0,0,1,7,24.34Z"></path>
                                <circle class="cls-2-fees" cx="41.5" cy="13" r="2"></circle>
                                <circle class="cls-2-fees" cx="9.5" cy="13" r="2"></circle>
                                <path class="cls-3-fees"
                                      d="M19.54,13.25h-3v2.93h3.38v.88H15.5V8.94h4.22v.88H16.51v2.57h3Z"></path>
                                <path class="cls-3-fees"
                                      d="M28.15,16.7a7.1,7.1,0,0,1-2.4.44,3.91,3.91,0,0,1-2.92-1.07,4.27,4.27,0,0,1-1.09-3A4,4,0,0,1,26,8.86a4.71,4.71,0,0,1,2,.37l-.25.85A4,4,0,0,0,26,9.74,3,3,0,0,0,22.81,13c0,2.06,1.19,3.28,3,3.28a3.14,3.14,0,0,0,1.34-.22V13.64H25.57V12.8h2.58Z"></path>
                                <path class="cls-3-fees"
                                      d="M30.69,9a10.75,10.75,0,0,1,1.94-.16,3.12,3.12,0,0,1,2.19.68,2.19,2.19,0,0,1,.68,1.69A2.46,2.46,0,0,1,34.9,13a3.18,3.18,0,0,1-2.39.89,3.35,3.35,0,0,1-.81-.07v3.25h-1Zm1,3.91a3.23,3.23,0,0,0,.83.09c1.22,0,2-.62,2-1.74s-.73-1.59-1.84-1.59a3.88,3.88,0,0,0-.95.09Z"></path>
                                <rect class="cls-4-fees" x="0.5" y="0.5" width="50" height="25" rx="2" ry="2"></rect>
                            </g>
                        </g>
                    </svg>
                </svg-icon>
                <span>{{$doctor->price_30_min}} جنية</span>
            </div>
            <div class="float-left">
                <svg-icon _ngcontent-serverapp-c130="" src="assets/images/profile/Video-Session.svg">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 54" style="width: 20px;">
                        <defs>
                            <style>.cls-1-video {
                                    fill: #3da8c0;
                                }

                                .cls-2-video {
                                    fill: #f4794c;
                                }</style>
                        </defs>
                        <title>session</title>
                        <g id="Layer_2" data-name="Layer 2">
                            <g id="Layer_1-2" data-name="Layer 1">
                                <path class="cls-1-video"
                                      d="M5.46,26.88v-18A1.68,1.68,0,0,1,7.92,7.36L25.3,16.48l17.32,9a1.65,1.65,0,0,1,0,2.88l-17.32,9L7.92,46.4a1.68,1.68,0,0,1-2.46-1.47Z"></path>
                                <path class="cls-2-video"
                                      d="M4.13,2a2.11,2.11,0,0,1,1,.25l22,11.56L48.94,25.17a2.11,2.11,0,0,1,0,3.66L27.16,40.19l-22,11.56A2.12,2.12,0,0,1,2,49.89V4.11A2.12,2.12,0,0,1,4.13,2m0-2h0A4.13,4.13,0,0,0,0,4.11V49.89A4.13,4.13,0,0,0,4.13,54a4,4,0,0,0,1.92-.48L28.09,42,49.86,30.6l0,0,0,0a4.1,4.1,0,0,0,0-7.12l0,0,0,0L28.09,12,6.05.48A4,4,0,0,0,4.13,0Z"></path>
                            </g>
                        </g>
                    </svg>
                </svg-icon>

                <span> +1000 جلية</span>
            </div>
        </div>


    </div>


    <div class="buttons-group">
        <div class="book open-doctor-modal" data-url="{{route('doctors.card', $doctor->id)}}">الحجز الان</div>
        <div class="view-profile" tabindex="0"> الصفحة الشخصية</div>
    </div>

</div>

resources/views/frontend/doctors/partials/results.blade.php
@foreach($doctors as $doctor)
    <div class="col-lg-4">
        @include('frontend.doctors.partials.doctor_grid')
    </div>
@endforeach

resources/views/frontend/doctors/partials/steps_section.blade.php
<section class="steps">
    <div  class="container align-items-center">
        <div  class="row animated slideInDown justify-content-center">
            <div class="col-md-12 text-center text-white fz24 mb-30">3 خطوات نحو حياة افضل</div>
            <div  class="col-md-2 step active">اختار المعالج</div>
            <div class="col-md-1 seprator"></div>
            <div class="col-md-2 step">حدد التاريخ والوقت</div>
            <div class="col-md-1 seprator"></div>
            <div class="col-md-2 step">أكمل عملية الدفع</div>
        </div>
    </div>
</section>

resources/views/frontend/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shezlong Task</title>
@include('frontend.partials.scripts.header')
<!-- Favicon -->
    <link href="{{asset('favicon.ico')}}" rel="icon" type="image/x-icon">
    @yield('css')
</head>

<body dir="rtl">


<!-- Start Page Wrapper  -->
<div class="page-wrapper">
@include('frontend.partials.header')
@yield('content')

<!-- Modal -->
    <div class="modal left fade" id="doctorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-body">

                </div>

            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div><!-- modal -->


    @include('frontend.partials.footer')

</div>
<!-- End Page Wrapper  -->


<a href="#" class="scrollup"><i class="flaticon-long-arrow-pointing-up" aria-hidden="true"></i></a>

@include('frontend.partials.scripts.footer')
@yield('js')

</body>


</html>

resources/views/frontend/partials/footer.blade.php
<section class="footer-copy-right bg-theme-color-2 text-white p-0">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <p class="text-white">© 2019, All Rights Reserved, Design & Developed By:<a href="#"> MFathi </a></p>
            </div>
        </div>
    </div>
</section>
<!-- Footer Style Seven End -->

resources/views/frontend/partials/header.blade.php
<!-- Header Section Start -->
<header class="header header-style-1 clearfix">

    <div class="menu-style bg-transparent menu-hover-2  clearfix">
        <!-- main-navigation start -->
        <div class="main-navigation main-mega-menu animated">
            <nav class="navbar navbar-expand-lg navbar-light">

                <div class="container">
                    <!-- header dropdown buttons end-->
                    <a class="navbar-brand" href="#">
                        <img id="logo_img" src="{{asset('assets/shezlong-logo-ar.png')}}" alt="">
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse"data-target="#navbar-collapse-1" aria-controls="navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>


                    <div class="collapse navbar-collapse" id="navbar-collapse-1">
                        <!-- main-menu -->
                        <ul class="navbar-nav ml-xl-auto">

                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">المعالجين </a>
                            </li>


                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ازاي تحجز جلستك؟ </a>
                            </li>

                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">الاختبارات النفسية</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">المقالات </a>
                            </li>
                        </ul>


                        <a class="nav-link">تسجيل الدخول</a>
                        <a class="nav-link"> انضم الينا كطبيب</a>


                        <a class="nav-link">English <i class="fa fa-globe" aria-hidden="true"></i></a>

                    </div>
                </div>
            </nav>
        </div>
        <!-- main-navigation end -->
    </div>

</header>
<!-- Header Section End -->

resources/views/frontend/partials/scripts/footer.blade.php
<!------------------------------------------
Main JavaScript
<------------------------------------------>
<script src="{{asset('assets/js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/script.js')}}"></script>

<script>
    $('#loading-image').bind('ajaxStart', function(){
        $(this).show();
    }).bind('ajaxStop', function(){
        $(this).hide();
    });
</script>

resources/views/frontend/partials/scripts/header.blade.php
<!------------------------------------------
      Main CSS File
    <------------------------------------------>
<link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/menu.css')}}">
<!-- Style CSS -->
<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{{asset('assets/css/responsive.css')}}">

resources/views/frontend/partials/sidebar.blade.php
<?php